const TopSliderMenuList = {
    Home:[
        {"name":"关注",key:""},
        {"name":"推荐",key:"recommand"},
        {"name":"抗击肺炎",key:""},
        {"name":"小视频",key:""},
        {"name":"热点",key:""},
        {"name":"科技",key:""},
        {"name":"健康",key:""},
        {"name":"上海",key:""},
        {"name":"在家上课",key:""},
        {"name":"财经",key:""},
        {"name":"军事",key:""},
        {"name":"娱乐",key:""},
        {"name":"文化",key:""},
        {"name":"历史",key:""}
    ],
    Xigua:[
        {"name":"推荐"},
        {"name":"直播"},
        {"name":"游戏"},
        {"name":"音乐"},
        {"name":"VLOG"},
        {"name":"综合"},
        {"name":"农人"},
        {"name":"美食"},
        {"name":"宠物"},
        {"name":"儿童"},
        {"name":"搞笑"},
        {"name":"时尚"},
        {"name":"懂车帝"},
        {"name":"体育"},
        {"name":"文化"},
        {"name":"手工"},
        {"name":"金秒奖"},
        {"name":"科技"},
        {"name":"广场舞"},
        {"name":"亲子"},
        {"name":"娱乐"},
        {"name":"旅游"},
        {"name":"情感"},
        {"name":"军事"},
        {"name":"NBA"}
    ],
    Movie:[
        {"name":"推荐"},
        {"name":"电影"},
        {"name":"电视剧"},
        {"name":"少儿"},
        {"name":"纪录片"},
        {"name":"综艺"},
        {"name":"动漫"}
    ]
}


export default{
    TopSliderMenuList
}